language: java
jdk:
  - oraclejdk8
env:
  - CODECLIMATE_REPO_TOKEN: a461c195ea03663c41ce8ee9501d06da3070bd84c91ca03ee7087e65bd4bf58d
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
