language: java
jdk:
  - openjdk8
env:
  - CODECLIMATE_REPO_TOKEN=a461c195ea03663c41ce8ee9501d06da3070bd84c91ca03ee7087e65bd4bf58d
before_install:
  - chmod +x mvnw
  - sudo apt-get install jq
  - curl $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("application/x-java-archive"))) | .[0].browser_download_url') -o codacy-coverage-reporter-assembly.jar
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
  - bash <(curl -s https://codecov.io/bash)
